service: serverless-e2e-tests

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-1
  memorySize: 256

functions:
  consumer-e2e:
    handler: consumer-handler.e2e
    environment:
      E2E_USERNAME: ${env:E2E_USERNAME}
      E2E_PASSWORD: ${env:E2E_PASSWORD}
      SLACK_WEBHOOK_URL: ${env:SLACK_WEBHOOK_URL}
    events:
     - schedule: rate(30 minutes)
